export const names = {
  it: [
    'Luigi',
    'Maria',
    'Giovanni',
    'Giuseppe',
    'Ricci',
    'Luca',
    'Nino',
    'Valentina',
    'Giulia',
  ],
  es: ['Maria', 'Pablo', 'Diego', 'Pedro', 'Esteban', 'Carmen'],
  fr: [
    'Mathilde',
    'Georges-Alain',
    'Adèle',
    'Justin',
    'Monique',
    'Morgane',
    'Ségolène',
    'Guy',
    'Nat',
    'Hans',
    'Mélanie',
    'Julien',
    'Olivier',
    'Robin',
  ],
}
